# Form implementation generated from reading ui file 'story_downloader/story_downloader.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.baseUrl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.baseUrl.setObjectName("baseUrl")
        self.verticalLayout.addWidget(self.baseUrl)
        self.slug = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.slug.setObjectName("slug")
        self.verticalLayout.addWidget(self.slug)
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.logBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.logBox.setObjectName("logBox")
        self.verticalLayout.addWidget(self.logBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Story Downloader"))
        self.startButton.setText(_translate("MainWindow", "Start Download"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
